### ISSUE TITLE
[Feature Request] World information Widget

### ISSUE THREAD

**Issue by yunarii** [una-xiv/umbra#104]
Hello!

Firstly, I want to express my admiration and gratitude for the plugin you’ve developed. It’s a fantastic change over the native UI, by far. So, thank you for your hard work!

I have one feedback request. Would it be feasible to please kindly incorporate the current World information as an optional Widget?

I think this is valuable information for multiple reasons. I can't express all, but here are some commonly shared experiences with other players: hunt trains, joining pf groups, checking alternate character retainers and/or submarines, finding better deals on market board items elsewhere, etc. Having this World information readily available on the server info bar has been incredibly useful in the past.

Recently, I activated the Umbra widget “Show server info bar entries from other plugins” to streamline the UI with the rest of Umbra, while hiding the native server info bar. It looks so much better, but it did sadly remove this ability to see the current World information.

I appreciate your time and hope all is well regardless :3

Alaina

**Comment by haroldiedema** [comment]
Just so I understand this correctly, are you referring to the world name that's on the native server info bar?
