### ISSUE TITLE
[BUG] The toolbar disappears

### ISSUE THREAD

**Issue by Dalek233** [una-xiv/umbra#105]
The toolbar disappears and does not appear. But the buttons are all there. Clicking the button still reacts to interact, but the top tool man is not displayed, it is useless to reload, it is useless to delete all configuration files and install again, and the top toolbar cannot be seen

**Comment by haroldiedema** [comment]
Which version of Umbra are you using?

**Comment by whoisfancy** [comment]
Same , Version Is v1.0.6.17

**Comment by whoisfancy** [comment]
I tried resetting Umbra and deleting plugins and folders, but to no avail.  The settings page can be opened normally, and the server bar is hidden normally, but the Umbra toolbar does not appear and I cannot click it.
![1718807137368](https://github.com/una-xiv/umbra/assets/51506435/af7cd920-db7b-4e7a-b5cc-4b43c0c7a849)

**Comment by haroldiedema** [comment]
I believe these issues are already fixed in 2.0. I'll leave this issue open until then.

**Comment by haroldiedema** [comment]
This may only happen in some very user/OS-specific situations if you have Dalamud's "Multi-monitor support" enabled. Unfortunately, Umbra does not support this option and causes all kinds of bugs.
