### ISSUE TITLE
[BUG] Custom button commands repeat

### ISSUE THREAD

**Issue by zbee** [una-xiv/umbra#112]
With version 2 Custom Buttons appear to repeat the command given to them based on how many times you have edited that Custom Button:
![image](https://github.com/una-xiv/umbra/assets/1582821/0b85cf05-1934-4ee0-8093-251270ddd42c)![image](https://github.com/una-xiv/umbra/assets/1582821/a6352b27-e186-474b-8c78-16b15241e2e8)

I typed the "editing now" message, and each time I did I edited the `Command` field of the same custom button.

Exact steps I took to see this bug:
- Added Custom Button widget
- Clicked the new button on the bar
- Edited the Custom Button
- Clicked the button again

**Comment by haroldiedema** [comment]
Hmm, it seems the `OnClick` event gets reattached every time you save the button 🤔 Feel free to open a PR if you can find it, otherwise I'll have a look at it tomorrow!
