### ISSUE TITLE
[Feature Request] Text Shadow and Outline

### ISSUE THREAD

**Issue by Aimsucks** [una-xiv/umbra#123]
I would love to see an option to toggle text shadows and outlines for the toolbar and window text.

**Comment by haroldiedema** [comment]
You can change those in the color profile. Text outlines can be "disabled" by just making the colors transparent.

1. Go to the Appearance tab
2. Create a new color profile if you're currently using a built-in one (it'll copy the existing settings to your new profile)
3. Activate your new profile
4. A whole bunch of color pickers will now appear below. Simply adjust these to your liking.
