### ISSUE TITLE
[Feature Request] Anti-aliasing for small icons

### ISSUE THREAD

**Issue by EBlaster** [una-xiv/umbra#129]
Right now the small icons have jaggies that don't happen on big icons, maybe having a separate small-sized icon set will help?
![icons](https://github.com/user-attachments/assets/f36b9931-96b5-45c4-b102-cbc869b45b64)

**Comment by haroldiedema** [comment]
The icons come from the game itself. There isn't much to be done in that regard. I've been trying to enable anti-aliasing on drawn images, but this also, unfortunately, has no effect. 

There isn't much I can do from a plugin's perspective to fix this.
