### ISSUE TITLE
[Feature Request] Click handlers for Gear Repair/Materia Extraction on Repair/Extract widget

### ISSUE THREAD

**Issue by NadyaNayme** [una-xiv/umbra#139]
Left click `/action Repair` to open gear repair menu

Right click `/action "Materia Extraction"` to open Materia Extraction menu

**Comment by haroldiedema** [comment]
Those options are already available from the popup.

**Comment by NadyaNayme** [comment]
My apologies. Something must've ate my left click when I tried it last night and right click does nothing so I assumed nothing was bound. I see the equipment list and at the bottom the repair / extract options in the menu when I left click now.

Not really sure what happened with my click but with how well polished everything is not all that surprised that it was user error in the end. ^^;
