### ISSUE TITLE
[Feature Request] A Menu/Widget for Free Companies

### ISSUE THREAD

**Issue by Rellawing** [una-xiv/umbra#140]
[Feature Request] A Menu/Widget for Free Companies

Assuming you belong to a FC, it would appear and give a quick list of guildies online, their locations and current job.

**Comment by haroldiedema** [comment]
This is not something that can be done unfortunately, because it requires data being fetched from the server. You can see this happening due to the "loading" of the official game window when you open your social window. Plugins are not supposed to do those kind of things.
