### ISSUE TITLE
[Feature Request] Display Job Icons For Party Members Not InZone

### ISSUE THREAD

**Issue by Rellawing** [una-xiv/umbra#141]
[Feature Request] Display Job Icons For Party Members Not InZone

Though I'm not sure this would be anything that you could or would touch/ since we have onscreen waymarks, I felt it might be possible. It'd be nice to be able to see what job people are on without opening the party list to see that or doing a Readycheck.

**Comment by haroldiedema** [comment]
Umbra doesn't have any party frames. Maybe this is better suited for DelvUI?

I also don't think this is possible, otherwise they would've implemented this already 😅
