### ISSUE TITLE
[Feature Request] Option in the "Inventory Space Indicator" widget to use Saddle Bags as source

### ISSUE THREAD

**Issue by billy-lack** [una-xiv/umbra#147]
Setting to make the "Inventory Space Indicator" show Saddle Bags. And also open the saddle bag when clicked on.

**Comment by haroldiedema** [comment]
UX-wise this wouldn't fit in the inventory space widget as-is, but I can make an option, similar to how the clock widget works, where you choose a "source", which is either Inventory or Saddlebag.

Then you can just make 2 widget instances, one for inventory and one for the saddle bags.

**Comment by billy-lack** [comment]
That sounds like an excellent solution!
