### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Megagalatkikarea2** [una-xiv/umbra#151]
What's the background color for the Toolbar called? I can't seem to find the correct one to make it seethrough.

**Comment by Megagalatkikarea2** [comment]
also i guess the shadow

**Comment by GayPotatoEmma** [comment]
The toolbar colors are under "Toolbar Colors" as Toolbar background 1/2. The toolbar shadow can be disabled in general settings > toolbar settings > enable toolbar shadow

**Comment by Megagalatkikarea2** [comment]
thank you very much
