### ISSUE TITLE
[Feature Request] Hide currencies

### ISSUE THREAD

**Issue by zbee** [una-xiv/umbra#152]
An option in the currencies menu to hide individual currencies would be amazing.

For example I do not earn or spend MGP, any of the hunt tokens, or skybuilder scrips. So I would toggle off those currencies, and ideally the whole `The Hunt` section would disappear because I toggled off all currencies under it.

**Comment by haroldiedema** [comment]
Can generate a list of checkbox nodes that serves as "ignored currencies" in the configuration based on the ID's in the enum values.

**Comment by haroldiedema** [comment]
There, now we can do this kind of stuff 😄 


![image](https://github.com/user-attachments/assets/0aeddeb8-5b51-433b-a5e1-bc2598af40f1)
