### ISSUE TITLE
[Feature Request] Icons for teleport/return/Eternity Ring

### ISSUE THREAD

**Issue by Megagalatkikarea2** [una-xiv/umbra#153]
i would like to have icons for teleport/return/Eternity Ring in the Travel submenu.
Also it's a nice touche that favorites are there but can they get icons as well? Maybe an option for it.

**Comment by haroldiedema** [comment]
Requires some adjustments in the MainMenuRepository. Should be doable though.

**Comment by haroldiedema** [comment]
![image](https://github.com/user-attachments/assets/c5e55732-f14d-4050-bdc4-afc4e6cf475c)
