### ISSUE TITLE
[Feature request] Place toolbar below /xldev when located at the top of the screen

### ISSUE THREAD

**Issue by NotNite** [una-xiv/umbra#16]
I believe `ImGui.GetFrameHeight` should match the size of the dev bar, and you can use PluginInterface.IsDevMenuOpen to see if it's currently drawing.

**Comment by haroldiedema** [comment]
Oh fiddlesticks. This used to work when I was using the workspace size. I think I messed up during some refactor work to use screen size/pos instead.

**Comment by haroldiedema** [comment]
Fixed in 1.0.2.0
