### ISSUE TITLE
[Feature Request] Sanctuary Indicator

### ISSUE THREAD

**Issue by ValkyrieOrange** [una-xiv/umbra#160]
It would be nice to have a sanctuary indicator similar to the vanilla XP bar. Either as a standalone item or as an option for the location or XP bar.

**Comment by haroldiedema** [comment]
Since the EXP bar is pretty 'cramped' as-is, I'd prefer this to be added to the Location widget instead. Since a location determines whether its a sanctuary or not, it would make sense to have it there. (Similar to where the instance number is)

**Comment by haroldiedema** [comment]
Information can be grabbed from `GameMain.IsInSanctuary()` from CS.
