### ISSUE TITLE
[Feature Request] Add map name option to Teleport

### ISSUE THREAD

**Issue by ValkyrieOrange** [una-xiv/umbra#161]
The vanilla teleport menu lists both the map name and aetheryte name. Example being "South Shroud - Quarrymill". It would be nice to have that as an option in the Umbra teleport menu as well. Maybe as an additional subheading in the list?

**Comment by haroldiedema** [comment]
![image](https://github.com/user-attachments/assets/fa4c161f-6e36-4ae3-ade7-4d7c06fd33ca)

Fixed 😄
