### ISSUE TITLE
[Feature Request] Add Information to the Teleport Location

### ISSUE THREAD

**Issue by RockHornetz** [una-xiv/umbra#162]
It would be great to add informations to the Teleport location like:
- Their Region (Not just the "town" name)
- If they are a Main City Hub (Icon)
- If they are the End-Game City Hub (Icon)
- If They are the main Teleport for a Beast Tribe (Icon)

If it's too much work to do maybe "just" adding a way to customize the name of each teleport + Adding Icon by ID would solve most of it.

**Comment by haroldiedema** [comment]
I did some digging into this, but unfortunately the icons isn't possible at the moment. I did however reworked the layout so that it shows the maps as well:

![image](https://github.com/user-attachments/assets/c595368d-7107-442a-8746-51eb5e1e9c46)
