### ISSUE TITLE
[Feature Request] Allow Durability/Spiritbond widget to display Average durability

### ISSUE THREAD

**Issue by katawajojo** [una-xiv/umbra#164]
What it says on the tin.

Currently, the Durability/Spiritbond widget only displays the Durability of whatever your lowest durability item is. However, it would be helpful for users to be able to choose to see the average durability for all items instead.

**Comment by Megagalatkikarea2** [comment]
I'd also love to have them as bars stacked over each other as a visual display

**Comment by katawajojo** [comment]
#200 would also be an extension of this, as it's also a super useful thing.
