### ISSUE TITLE
Toolbar visibility setting for PvP

### ISSUE THREAD

**Issue by NekoEnzeru** [una-xiv/umbra#165]
I don't know if it would be possible or not but, perhaps a toolbar visibility setting that hides the toolbar during pvp but not pve duties?

**Comment by haroldiedema** [comment]
You can do this by going to General Settings -> Toolbar Settings.
There's an option to auto-hide the bar during pvp duties.

**Comment by NekoEnzeru** [comment]
I have no idea how I didn't see that before. Apologies.
