### ISSUE TITLE
[Feature Request] Add ability to favorite teleports for increased visibility

### ISSUE THREAD

**Issue by nightpanda2810** [una-xiv/umbra#166]
LOVE the new teleport menu, removed an entire QoL bar! 

One thing I'd like to see added is an ability to favorite/highlight specific teleports. For example, if I were to favorite Base Omicron (beast tribe/society port), it would be highlighted in the menu.

A separate favorites menu would also be great, but simply highlighting would be good enough for me!

**Comment by haroldiedema** [comment]
Since the base game only allows 3 favorites, I think having a custom favorites list would be better, since we wouldn't be limited by the max of 3.

**Comment by nightpanda2810** [comment]
To clarify, I meant within Umbra itself, not based on the games favorites. With my QoL bar for example, my "favorites" as I describe them here had a different icon and color that indicated they were a hub or a beast tribe, making them easier to spot if I didn't remember the name of the teleport. 

Hopefully this better articulates what I meant! (Although the custom favorites list is also a great idea!)

**Comment by haroldiedema** [comment]
Info for myself: 
![image](https://github.com/user-attachments/assets/04b80745-4998-4b30-941f-fb1a089999be)
