### ISSUE TITLE
[Feature Request] Make clock visibility & time-string respect the game settings.

### ISSUE THREAD

**Issue by haroldiedema** [una-xiv/umbra#17]
The Character Settings in game (UI Settings) allows the user to show/hide individual clocks. The Clock widget should adhere to this.
![image](https://github.com/una-xiv/umbra/assets/567518/29a4fd84-0028-47ad-847f-674522b6694a)

An extra option in Umbra should be added that allows the user to change the order around.

**Comment by LTS-FFXIV** [comment]
additionally, the clock should respect hour formating, as at the moment it seems to be defaulting to 24hour clock
![image](https://github.com/una-xiv/umbra/assets/127939494/abd18011-7004-4211-bc56-49a83c448280)

**Comment by haroldiedema** [comment]
The three features combined would effectively be a full rewrite of the clock.

**Comment by haroldiedema** [comment]
Another one that belongs here:

 - Add an option to show seconds for each clock.

**Comment by haroldiedema** [comment]
> Small change, i'd love if i could change the ET time to ST or LT
> so i have LT and ST as the 2 active ones, i couldn't care less about
> ET ^^' i'm sure some people would love that too
