### ISSUE TITLE
[Font Request] axis-ffxiv

### ISSUE THREAD

**Issue by Nillinn** [una-xiv/umbra#180]
Could you take a look into adding the "axis-ffxiv" font? DelvUI plugin has it.
I think this is the closest we can get to FFXIV's default font, using Dalamud. It would look quite nice in Umbra's widgets.

**Comment by haroldiedema** [comment]
Due to a licensing issue, this isn't possible.

If you can find or buy the font itself, just install it on your local machine. After a game restart, the plugin will see it and it'll become selectable.
