### ISSUE TITLE
[Bug] Clipping issues in OOBE wizard 

### ISSUE THREAD

**Issue by dakkidaze** [una-xiv/umbra#183]
The text in OOBE parts seems to have fixed length and clipped the translation.
![图片](https://github.com/user-attachments/assets/f09aa1d8-9612-45da-916e-776668c7c5c7)

**Comment by haroldiedema** [comment]
Since the bug itself is part of the drawing library, I've moved the issue there: https://github.com/una-xiv/drawing/issues/6
