### ISSUE TITLE
[Feature Request] Support overriding all languages that Dalamud supports, and fallback to English.

### ISSUE THREAD

**Issue by dakkidaze** [una-xiv/umbra#184]
The plugin only supports EN, DE, FR, JA to override dalamud language settings, but one can still load translation of other languages if
1. Dalamud is set to desired language;
2. The json file exists.
![图片](https://github.com/user-attachments/assets/49e0e4eb-4c4c-49b9-a598-c9fe7862633c)

I would like to request a feature that checks if a translation file exists and automatically add the language to the drop down list.

**Comment by haroldiedema** [comment]
I've added ZH to the list. Should be up in the next update 😄
