### ISSUE TITLE
[Feature Request] Option in the Inventory Space Indicator to show Current Total out of Possible Space

### ISSUE THREAD

**Issue by vrenlin** [una-xiv/umbra#185]
Currently the Inventory Space Indicator shows the Free Space out of Total Possible space in bags.
![image](https://github.com/user-attachments/assets/41c5bdb9-0709-4aa6-aca1-5033319c5169)

I would love to see an option to instead see Current Count of Items in Bag over Total Possible Space.

So in the above example, instead of **114/140** I would see **26/140**

**Comment by haroldiedema** [comment]
I've fixed this by showing used slots by default to be consistent with how the game does it. It'll be available in the next update.
