### ISSUE TITLE
[Minor Visual Bug] Unnecessary Fade-Out during Cutscenes.

### ISSUE THREAD

**Issue by RockHornetz** [una-xiv/umbra#189]
When the Bar is set to auto-hide during Cutscene and a cutscene start after a dialogue (where the bar is already hidden because of the dialogue), instead of doing nothing because it's already hidden it fade-out from opaque to transparent.
Note: Chat2 is having the same kind of problem when manually hidden with the built in button and a cutscene starts.

**Comment by haroldiedema** [comment]
From a plugin's perspective there isn't much you can do about this unfortunately.
