### ISSUE TITLE
[Bug] Crash on bringing up gear switcher

### ISSUE THREAD

**Issue by Magusware** [una-xiv/umbra#190]
Not really sure how to give information on this one.
When I bring up the gear switcher it immediately crashes XIV, gets the dalamud prompt to restart normally etc.

I thought might be some config I messed up so I removed umbra and deleted the config data from roaming. Essentially a clean install of Umbra. With the default config from the wizard gear switcher still crashes when I try to bring it up.

I know it's not widespread as someone I know who uses as well does not have this issue.

**Comment by Megagalatkikarea2** [comment]
i do have it too, as well as a friend of mine

**Comment by Magusware** [comment]
I grabbed the latest code and loaded it as a dev plugin, that worked fine. So whatever the problem is it's been fixed between whenever the last build was made available through dalamud and the latest commits.

**Comment by haroldiedema** [comment]
Yes, this was a known issue that I've been working on fixing since last night. It has been fixed now and will be available to you all in 2.0.10. It's in review at time of writing this.
