### ISSUE TITLE
[Feature Request] Add option for widgets to automatically open their popup when moused over

### ISSUE THREAD

**Issue by Kamayana** [una-xiv/umbra#191]
It'd be very nice if there was a setting to make widget menus automatically open when mousing over their widget. I never move my mouse to the top of the screen so requiring a click to open the menus seems unnecessary. The main reason I'd like this is for the gearset switcher, which I'd need to open quite often, and that extra click is just enough friction to make me forego it for my pre-existing gearset switching hotbar.

This behavior is even already in the plugin, technically - if you click to open a menu you can mouse over other widgets to switch to their popup.

Would work as either a global or per-widget setting, though I'd prefer global since I'd want them all to do this.

**Comment by Kamayana** [comment]
It looks like simply changing `OpenPopupIfAnyIsOpen` in these lines to `OpenPopup` would accomplish the behavior I'd like, but obviously you'd want to tie that to a plugin setting which would take a fair bit more work - for one thing all of the existing OpenPopupDelayed events would need to be updated when the setting is changed.

https://github.com/una-xiv/umbra/blob/a7f4dc959becda3142b3c72954a555a132645579/Umbra/src/Toolbar/Widgets/System/WidgetManager.cs#L154-L155
https://github.com/una-xiv/umbra/blob/a7f4dc959becda3142b3c72954a555a132645579/Umbra/src/Toolbar/Widgets/System/WidgetManager.cs#L178-L179

**Comment by haroldiedema** [comment]
I really wouldn't want to do that, since they won't close when your mouse exits the popups. That's going to be an annoying hot mess from a UX perspective.

**Comment by Kamayana** [comment]
Yeah, you'd also want popups to collapse when the mouse isn't over them or the umbra bar.

**Comment by haroldiedema** [comment]
I'm sorry but I can't do that. Popup open/close-states are tied to the window-focus system of ImGui to determine whether they should be visible or not. Moving away from that would break other things like context menus and potentially conflict with other plugins.
