### ISSUE TITLE
[Bug] Toolbar not starting in hidden state on login with auto-hide enabled.

### ISSUE THREAD

**Issue by Nillinn** [una-xiv/umbra#193]
Toolbar doesn't hide itself upon login, unless hovering the mouse over it.
Any way for the plugin to check if the "hide toolbar" setting is enabled upon login and make the bar hide itself automatically?

**Comment by haroldiedema** [comment]
Thanks for reporting! This is actually a bug 😅

**Comment by Drakime** [comment]
I also noticed this in the past, but I don't actually think this bug exists anymore. Unless it's still reproducible. At the most, the toolbar flashes briefly during the loading screen, and then hides correctly.

**Comment by Nillinn** [comment]
It was fixed. Thank you.
