### ISSUE TITLE
[Feature Request] Hide iLVL from Gearset Switcher widget

### ISSUE THREAD

**Issue by RavenRaconteur** [una-xiv/umbra#194]
Hello! I'd really like it if we could hide the item level text from the gearset switcher widget without hiding the class/job name. Is this doable? Thanks!

**Comment by haroldiedema** [comment]
- Add option to show/hide the item level on gearset switcher buttons to declutter the interface a bit. Enable this by default to retain original looks.

**Comment by haroldiedema** [comment]
@RavenRaconteur Just to clarify, you are talking about the gearset buttons in the popup right? Or do you mean the toolbar widget button itself?

**Comment by RavenRaconteur** [comment]
I was personally talking about the toolbar widget itself. I don't mind the item levels in the popup, but would welcome the option to hide those if others want to.

**Comment by haroldiedema** [comment]
So it's just one label then, correct? (The name of the gearset, which happens to be the job name by default)

**Comment by RavenRaconteur** [comment]
That's right.
