### ISSUE TITLE
[Feature Request] Teleport - Option to default to opening favorites rather than current location expansion

### ISSUE THREAD

**Issue by nightpanda2810** [una-xiv/umbra#195]

**Comment by nicuity** [comment]
Just to add, sorting by expansion would make it nice and tidy :). Or maybe just a sort option in general if others prefer the default.

**Comment by haroldiedema** [comment]
@nicuity You can sort the favorites yourself. Try right-clicking on one of the entries 😉

**Comment by nightpanda2810** [comment]
I suspect @nicuity meant having columns per expansion, like the columns per area in the expansion tabs do now. Which I agree with, would be great!
