### ISSUE TITLE
[Feature Request] Job Switcher Bar - Add functionality for multiple columns and rows

### ISSUE THREAD

**Issue by Kameily** [una-xiv/umbra#196]
It would nice to be able to sort the jobs into additional collumns/rows. Here is a poorly done example in paint for what I would like.
![example](https://github.com/user-attachments/assets/99608020-5dc5-4c02-b369-ca13c704a8cc)

**Comment by haroldiedema** [comment]
Heya! Thanks for the suggestion. However this unfortunately isn't possible since there is a hard limit of 3 columns in the current architecture of the widget. Implementing what you're asking would entail a full refactor/rewrite of the entire widget.
