### ISSUE TITLE
[Feature Request] Add the ability to display umbra on the side of the screen

### ISSUE THREAD

**Issue by stevanhi** [una-xiv/umbra#199]
I've attached an image of what I mean. It would be a mostly icon only deal in terms of usability, but I think implementing it would still be worthwhile.

![UcCVNko](https://github.com/user-attachments/assets/d42d6d72-2452-4d6c-8b35-64387ae14105)

**Comment by haroldiedema** [comment]
I'm sorry, but no. That's not happening. All widgets are _designed_ to be horizontally flexible. Having this as an option would look incredibly chaotic and bugged.
