### ISSUE TITLE
[Feature Request] Add item quality options to custom menus

### ISSUE THREAD

**Issue by GayPotatoEmma** [una-xiv/umbra#206]
Currently item buttons do have the ability to let you select priorities for item qualities however adding an item in a custom menu does not. This makes it so that you can't use HQ items if they're in a custom menu

Edit: mixed up custom buttons and item buttons, its the middle of the night dont judge me 😅

**Comment by haroldiedema** [comment]
There was a bug in there that caused it to only pick up NQ items. This has been resolved.

Currently, for as long as the option to set the behavior isn't available, it defaults to "HQ before NQ".
