### ISSUE TITLE
[BUG] Wrong position of the button in companion widget for other languages

### ISSUE THREAD

**Issue by Lanicia** [una-xiv/umbra#212]
The button is incorrectly positioned for the companion widget in other languages. For example, in French the "Feed" button is hidden : 
![image](https://github.com/user-attachments/assets/fdb8ac87-a23a-4bdf-b75c-b31b96ed0bb5)

**Comment by haroldiedema** [comment]
Oh dear, it seems the info button is too wide. What would be an appropriate French translation for the left button that would be much shorter?

**Comment by GayPotatoEmma** [comment]
Infos du compagnon could work

**Comment by haroldiedema** [comment]
Still too long. I'll use "Information" for now.
