### ISSUE TITLE
[Bug] Weather and Location Glitching

### ISSUE THREAD

**Issue by Rellawing** [una-xiv/umbra#217]
![GlitchyWeatherLocation](https://github.com/user-attachments/assets/9900fe27-02a9-4e6c-a865-a75d4a7bc363)

As you can see, it's really unstable looking ever since tonight's update. It's the first time I've seen anything go wrong with Umbra. I hope you can fix it soon. I might get epilepsy from watching it too long. XD

**Comment by Rellawing** [comment]
Update: I think it's the icon that's jittering. When I separated them left and right, the only thing that jitters is the icon.

![GlitchyWeatherIcon](https://github.com/user-attachments/assets/c21e7eb7-785e-48df-beab-406e4aa042a2)

**Comment by haroldiedema** [comment]
I've already found this and fixed it for the next update 2.1.5.
