### ISSUE TITLE
Feature Request: Option to display district and location names side by side instead of both centered.

### ISSUE THREAD

**Issue by Dajova** [una-xiv/umbra#225]
Hey, love the plugin and the options it have.
However, i've found that there is just a bit short on space when using the "Location" widget as they cram to fit within the same location. Isn't it better to to put them side by side instead, specially when the actual toolbar is very short?

**Comment by haroldiedema** [comment]
Heya!

Since 2.1.4, you can already do this yourself by making 2 instances of the Location widget. One shows only the location, the other only shows the district. This would effectively have the same effect.

**Comment by Dajova** [comment]
I am checking the options and it's *not* there. And im on 2.1.5.
![image](https://i.imgur.com/s9uf82w.png)
... unless you forgot to push the commit or something? All im getting is either just the location or both. Just district is not there.

**Comment by haroldiedema** [comment]
My bad. I got this confused with the weather forecast widget 😅

**Comment by Dajova** [comment]
Alright, no worries. Take your time 👍
