### ISSUE TITLE
[Feature request] toggle button on Plugin list

### ISSUE THREAD

**Issue by mehistaken** [una-xiv/umbra#230]
Add a toggle button on the plugin list popup to allow quick enable/disable of specific plugins

**Comment by haroldiedema** [comment]
You can do this by enabling the quick access to widget settings under General Settings -> Toolbar Settings. Hold ctrl+shift and right-click on any widget to quickly access its settings.

In the case of the plugin list widget, this will allow you to quickly toggle what is visible in the popup menu.
