### ISSUE TITLE
[BUG] The weather in Eureka Hydatos isn't always accurate.

### ISSUE THREAD

**Issue by haroldiedema** [una-xiv/umbra#24]
I've noticed in Eureka (Hydatos) that the weather isn't always accurate. It seems there are some conditionals there. I'm still not entirely sure if it's only the weather change when Ovni spawns or if there are other factors. Some help here would be greatly appreciated.

It may even happen that the weather says that its raining, while in fact the weather is clear.

**Comment by MKhayle** [comment]
Ovni's weather exists in addition to the current weather (and the current weather applies its effect even during Ovni's weather)

**Comment by haroldiedema** [comment]
Fixed & verified in 1.0.4.4 - https://github.com/goatcorp/DalamudPluginsD17/pull/3484
