### ISSUE TITLE
[Bug] ex-party member names show in map

### ISSUE THREAD

**Issue by mehistaken** [una-xiv/umbra#240]
After coming out of a Alliance Raid roulette (Syrcus Tower) several party members' name appear as world markers OOB. Not all party members are shown (just 4) and they are from a mix of home worlds. Markers are displayed even if "Party Members" is deselected from the config.
Screenshot attached - names blurred out for privacy sake
![Screenshot 2024-07-27 194142](https://github.com/user-attachments/assets/32a5d218-6f1b-4516-99ef-a1fdb1f22bc7)

**Comment by GayPotatoEmma** [comment]
Hi, this issue should be (hopefully) addressed in 2.1.9, please wait for this update to roll out.
