### ISSUE TITLE
[Bug] When you have a sub-menu (pop-up) open and happen to hover above something else that also have sub-menus, that opens up.

### ISSUE THREAD

**Issue by billy-lack** [una-xiv/umbra#243]
When you for example have the Gearset picker open, and you happen to hover above the teleport widget, the teleport widget opens up. This happens without holding any mouse buttons down or extra clicking.

**Comment by haroldiedema** [comment]
That's not a bug but by design. It behaves the same as any toolbar menu in any application. 
For example, open Notepad then click on the "File" menu. While it is open, move your mouse to Edit or View.
