### ISSUE TITLE
[Feature Request] XIV Messenger Integration

### ISSUE THREAD

**Issue by rmaroney** [una-xiv/umbra#246]
Just a possible integration with [XIV Instant Messenger](https://github.com/NightmareXIV/XIVInstantMessenger) so that it moves it from a separate window to part of the toolbar that I can click to open a dropdown to see messages/tells.

**Comment by haroldiedema** [comment]
I like the idea, but this would require XIV instant messenger to expose IPC methods other plugins can hook into. Otherwise there is no way to interact with it, or read information from it, like open chats, etc.

You might want to submit a feature request there first.

**Comment by AsunaTsuki** [comment]
@haroldiedema We can add an IPC to XIV Instant Messenger. What would you like exposed in the IPC?

**Comment by haroldiedema** [comment]
Oh sweet!

- `uint GetConverationCount()` - (e.g. open windows or tabs to determine if the widget should be visible)
- `uint GetUnreadMessages()` - For when the windows are hidden, e.g. during combat.
- `List<string> GetSenderList()` - For showing a list of open conversations (maybe this should be a dict?)
- `void OpenWindow(string? id)` - Opens the window or tab of a conversation (using the id of the GetSenderList)?

Maybe I'm missing something, but something like this would be neat.

**Comment by Limiana** [comment]
I have added some IPC: https://github.com/NightmareXIV/XIVInstantMessenger/blob/master/Messenger/Services/XIMIpcManager.cs
I believe this should be enough, but if not I can add more methods as well

**Comment by haroldiedema** [comment]
Added in 2.3.3
