### ISSUE TITLE
[Bug] Widgets do not resize themselves automatically when the text inside them changes

### ISSUE THREAD

**Issue by masanbol** [una-xiv/umbra#250]
This is most obvious with the location and gearset switcher widgets since their text changes frequently. The current behavior leaves blank space until you mouse over the widget, at which point it resizes to fit the current text.

![Screenshot 2024-08-04 161943](https://github.com/user-attachments/assets/872b1365-18c8-4c91-83eb-ff0b94580606)

**Comment by haroldiedema** [comment]
Confirmed 👍 

I noticed this happening with the weather forecast widget as well.
