### ISSUE TITLE
[Feature] Rollover or columns on Plugin list if it reaches a certain length

### ISSUE THREAD

**Issue by masanbol** [una-xiv/umbra#251]
Currently the Plugin widget creates a single column list, and it's possible to have enough plugins installed that they go off the screen. Scrolling or multiple columns would be helpful.

**Comment by GayPotatoEmma** [comment]
This has been addressed in the Discord a few times already and is not planned due to technical limitations with the current system. Your best bet is to simply disable the plugins that you don't need in there in it's widget settings and potentially add a second instance if it's still too long.
