### ISSUE TITLE
[Feature Request] Allow changing font size on toolbar without affecting settings menu

### ISSUE THREAD

**Issue by Naixatloz** [una-xiv/umbra#252]
I want to increase the height of my toolbar while keeping the font size the same, in order to neatly fit UI from other plugins onto it, but there's currently no way to do this without also resizing the font in the settings menu and making it nearly unreadable. I think the ideal would be to be able to change the font size of each widget individually.

---

![1](https://github.com/user-attachments/assets/c0a6dbeb-d3c9-476c-9506-5a045d0fe229)
Doesn't look good, let's try and make these more even...

![2](https://github.com/user-attachments/assets/fa1ccb57-ef38-4f2c-a038-0ceeae79d788)
Oh no.

**Comment by Dajova** [comment]
I second this, having separate fonts to the option menu and toolbar itself would be a blessing.

**Comment by haroldiedema** [comment]
Done and done 👍 

Feature will be available in 2.2.19
