### ISSUE TITLE
BUG: Update broke the toolbar

### ISSUE THREAD

**Issue by Megagalatkikarea2** [una-xiv/umbra#253]
Hello it's me again,
after the last update the toolbar went black (except the ping plugin for some reason). Seems to work fine despite this. I duno how to provide additional details. reloading and turning some settings didn't do anything.
![image](https://github.com/user-attachments/assets/30215aa0-0328-4227-8127-83081901c7b8)

**Comment by haroldiedema** [comment]
Can you try turning off multi-monitor support if you have it enabled?

**Comment by Megagalatkikarea2** [comment]
that did it, thx
