### ISSUE TITLE
[Bug] Travel category of the "Main Menu Button" widget non-functional since 2.2.14 update

### ISSUE THREAD

**Issue by KalChoedan** [una-xiv/umbra#255]
All items in the teleport menu are greyed out since 2.2.14. Sometimes the cost isn't populating either (i.e. all entries show as 999gil.)

**Comment by haroldiedema** [comment]
Do you perhaps mean the Travel category of the "Main Menu Button" widget?

**Comment by KalChoedan** [comment]
Removing it and re-adding it seems to have resolved the issue though.

**Comment by KalChoedan** [comment]
I spoke too soon - not sure what's triggering it. Mostly the menu is populated (with prices) but greyed out. Sometimes it works as normal. Sometimes it's both greyed out and the prices are all listed as 999gil.

**Comment by haroldiedema** [comment]
I got it fixed for the next update 👍

**Comment by KalChoedan** [comment]
To be fair the new Integrated main and Teleport widgets are better anyway :)

**Comment by masanbol** [comment]
> To be fair the new Integrated main and Teleport widgets are better anyway :)

There's still some things we need to use the travel menu for, such as private housing, since those aren't in the Teleport widget. I also ran into this earlier so thanks for reporting it 😄

**Comment by KalChoedan** [comment]
> There's still some things we need to use the travel menu for, such as private housing, since those aren't in the Teleport widget. 

[Feature Request] ?

**Comment by haroldiedema** [comment]
> > There's still some things we need to use the travel menu for, such as private housing, since those aren't in the Teleport widget.
> 
> [Feature Request] ?

No. The teleport widget pulls Aetherytes from the game. It does nothing else.
