### ISSUE TITLE
[Feature request] Colorize Retainer widget icon based on retainer Venture status

### ISSUE THREAD

**Issue by masanbol** [una-xiv/umbra#256]
Would be nice to have an optional setting to colorize the Retainer widget icon if your ventures are complete/in progress/not sent. Maybe default gray if none are active, yellow if they are in progress, and green if they are complete?

Thanks for the consideration!

**Comment by haroldiedema** [comment]
No sorry. This information is available after a server request. Because Umbra is an official Dalamud plugin, it has to adhere to the 1:1 rule, meaning manual interaction is _required_ before retrieving the info from the server. This means that this info is only available when you open the popup.
