### ISSUE TITLE
[Bug] Incorrect GC seal cap

### ISSUE THREAD

**Issue by foophoof** [una-xiv/umbra#26]
It looks like the cap in the currency tab for GC seals is wrong, it's showing 200,000, but the cap for me currently is 90,000 (which I think is the max cap?)

![Screenshot of currency tab in Umbra, showing 78,967 / 200,000 flame seals](https://github.com/una-xiv/umbra/assets/22138688/9bda40c3-59f3-4b36-ba67-576faeae093b)

I'm on v1.0.0.2.

**Comment by haroldiedema** [comment]
I think GC seals require some custom logic for them because the cap is based on your GC rank. Apart from detecting _which_ GC you are a member of, I haven't worked on anything else related to this yet.

**Comment by haroldiedema** [comment]
https://github.com/NotAdam/Lumina.Excel/blob/master/src/Lumina.Excel/GeneratedSheets/GrandCompanyRank.cs

**Comment by haroldiedema** [comment]
![image](https://github.com/una-xiv/umbra/assets/567518/61ff9b1d-7e99-424d-8254-4099002b1095)

Fixed in the upcoming 2.0 version.
