### ISSUE TITLE
Square not Rounded Corners, 

### ISSUE THREAD

**Issue by RyudoGaming** [una-xiv/umbra#261]
Please could we get an option for Square corners and not rounded, back when Umbra first started I was able to modify the code myself to do this but Umbra has become so big now its way out of my league to change it all, everything else in my FF game is Square,!

My map is Square, Skills are Square, Dalamud is Square, Inventory, Job bars, etc are all square but Everything in Umbra is rounded,

Please could we get an option for things to be Square and not rounded as I really can't stand rounded corners. 

Thanks for everyone's hard work on this plugin! 

![image](https://github.com/user-attachments/assets/031dacfd-7c9b-4158-9e01-2dd40609be4b)

**Comment by haroldiedema** [comment]
I saw your feedback message that you've given earlier today. I'll have a look at this later 👍

**Comment by RyudoGaming** [comment]
Sweet! Thanks so much!

**Comment by haroldiedema** [comment]
Fixed in 2.3.3

**Comment by RyudoGaming** [comment]
God damn Thank you so much!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
