### ISSUE TITLE
Inherit macro icon and/or set custom icons on shortcut panel

### ISSUE THREAD

**Issue by Drakeny** [una-xiv/umbra#262]
(Skimmed through the shortcut refactor and this already _seems_ to be planned or accounted for future updates but i'm posting anyway just to be sure :) )

Currently when adding macros to the shortcut panel it doesn't inherit the macro icon set with "/micon", it would be wonderful if that was the case. While I'm not sure if this is feasible thing to achieve an alternative would be the ability to set custom icons like we can do with others buttons in umbra, for example: a small IconID selection box within the context menu of a shortcut slot, above the controls for copy/paste/clear.

**Comment by haroldiedema** [comment]
Heya,

It actually already does this, to an extent. You can either use Gearset icons, or use Simple Tweaks extended macro icon tweak. Both of these are currently implemented. The others work with strings that users can give, which is a pretty big pain to implement properly to make it support multiple client languages.

Both of these currently work as intended: (replace # with a number)
```
/micon # gearset
/micon # id
```

**Comment by Drakeny** [comment]
Oh, cool, I wasn't aware of that tweak, yup, that's what I wanted!

Also, I don't know if this is documented anywhere, if it isn't, I don't really have a suggestion on where/how to do it other than keeping my example/suggestion on the OP(iconid selection on context menu) and using it as an override, think it would be a clearer user experience independent of having previous knowledge of functionality of other plugins.

So if the above suggestion is inviable or not a direction you'd want to take we can close this, as my "own issue" is now resolved.

Either way, thank you very much!
