### ISSUE TITLE
Stacked Clock 24 hour time

### ISSUE THREAD

**Issue by ripsnortntear** [una-xiv/umbra#277]
please add the ability to change from 24 hour to 12 hour time to the stacked clock.

thanks

**Comment by Mokura** [comment]
This should already be possible.

![image](https://github.com/user-attachments/assets/59d091be-e444-4093-a844-9c140b778525)


Use these variables: https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
