### ISSUE TITLE
[Bug] Toolbar not filling the entire edge of the screen

### ISSUE THREAD

**Issue by bonsaibnuuy** [una-xiv/umbra#28]
The bottom and right edges of the toolbar don't fit the whole screen - not a big deal, but mildly annoying.  Resolution is 2560x1440.
![image](https://github.com/una-xiv/umbra/assets/95835547/6d1b2c2a-96ff-4f29-a6e9-794d9e11c62f)

**Comment by haroldiedema** [comment]
I wonder if this happens with other plugins as well that snap things to the edges based on the reported screen size from ImGUI 🤔 

Can you tell me if you're running in borderless, windowed or fullscreen?

I'm running on 3440x1440 myself and haven't noticed anything like this before.

**Comment by bonsaibnuuy** [comment]
borderless!
