### ISSUE TITLE
Option to retain in game server info bar

### ISSUE THREAD

**Issue by EdwardShipp** [una-xiv/umbra#283]
Would be nice if there was some way to have the server info for the easy view while allowing the drop down. Currently to have a persistent bar I need to have the umbra bar locked.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by alexpado** [comment]
Do not download this file until this get reviewed. It might be a false positive, but don't use it to be safe.

![image](https://github.com/user-attachments/assets/fb62bc7a-89ec-4497-9e59-3f3d907ec3a4)

**Comment by haroldiedema** [comment]
There is an option in the widget settings of the server info bar widget to keep the original one visible.
