### ISSUE TITLE
Umbra XIV caused the game to crash on the Dalamud Chinese client due to a font error

### ISSUE THREAD

**Issue by RedAsteroid** [una-xiv/umbra#286]
Dalamud Chinese client defaults to using the font ``NotoSansCJKsc-Medium.otf`` instead of ``NotoSansKR-Regular.otf``, which will cause the game to crash on the Chinese server.

**Comment by pingmoogle** [comment]
国服启动器更新后，Umbra已经可以使用了
It has been solved after a DalamudCN launcher update
