### ISSUE TITLE
[Feature Request] Allow for setting custom time strings in C#

### ISSUE THREAD

**Issue by bonsaibnuuy** [una-xiv/umbra#29]
Currently, there's a simple tweak that allows you to do this - I'd like to be able to set it up to have Eorzean Time display both 12-hour and 24-hours and the Local Time display the 12-hour time and date.

Furthermore, it'd be nice to be able to add your own widgets from other, similar tweaks, like FPS, Ping, or current world.  This is how I currently have my server bar set up.

![image](https://github.com/una-xiv/umbra/assets/95835547/dba13136-144d-4794-ada2-e9754e109029)

**Comment by haroldiedema** [comment]
Thanks for the suggestion! The server info bar is already in, just waiting for the new version to appear in Dalamud's repo.

The time strings has already been suggested in #17 , so I'll close this one as duplicate.
