### ISSUE TITLE
[feature request] exclude aetherytes

### ISSUE THREAD

**Issue by hhharkness** [una-xiv/umbra#304]
hi there! love the new adjacent area option, but didn't expect it to include aetherytes - would it be possible to add an option to exclude them? thanks!

**Comment by haroldiedema** [comment]
Oh, it showing retainer bells and stuff is an accidental left-over of my debugging mess last night 😅  I'll get rid of that.

**Comment by haroldiedema** [comment]
Fixed in 2.3.4 (work in progress)
