### ISSUE TITLE
[Feature Request] Add config to offset the center element for each side

### ISSUE THREAD

**Issue by wolfcomp** [una-xiv/umbra#35]
Would be nice to have an option that says to offset the left element and right center element x pixels to each specific direction.

![center line](https://screenshots.wildwolf.dev/ffxiv_dx11_66715d036a.png)
![IMG_20240428_145441](https://github.com/una-xiv/umbra/assets/4028289/f544c83b-3ce6-4a14-a323-0e6987290bd2)

**Comment by haroldiedema** [comment]
🤣

Yes. We can do that. To be clear, what you're asking for is a setting that controls the _spacing_ around the weather icon, right?
In your case, to allow the text to appear next to your webcam clamp 😛

**Comment by wolfcomp** [comment]
Yep split where the red line is so weather is on one side the location on the other

**Comment by haroldiedema** [comment]
Oh, I would've hoped the weather icon could stay in the middle 😂

**Comment by wolfcomp** [comment]
If you calculate the center position based on the elements with adding a `ImGui.Dummy` where that red line is, that shouldn't be an issue. If you do it each element, have fun 😛

**Comment by haroldiedema** [comment]
Oh no, it's not that complex. All I need to do is increase the margin value of the element.
