### ISSUE TITLE
[Feature Request] scaleable toolbar, widget menues and text

### ISSUE THREAD

**Issue by Yalessa** [una-xiv/umbra#39]
I'd love to adjust the height of the bar and make it smaller. The whole thing is so big on a 1080p monitor and the widgets are too big, the text is too big and there's no way yet to scale it all down so that it's not so prominent. Would love to be able to split the clocks and have them next to each other and not above each other. This way you can scale the clocks down and you would still be able to read them. Just like Vanilla FFXIV shows you the clocks.  I'd love to scale down the widget menues themselves too if they're too big. I don't need the text to be so big on everything, but would love to increase the size where it's necessary because of downscaling the toolbar.
Comparing umbra on my 1920 x 1080 monitor with my bfs 2560 x 1440 monitor is a huge difference. Everything is smaller and spacey. I want to be able to adjust it so that it can look like this too as good as it can. 
I look forward to the next updates, it looks so promising and has so many cool features! Just looks better on monitors with a higher resolution than 1080p and I want to be able to adjust it to my needs. (I'm very much reminded of TitanBar from WoW and I loved it all the same xD)
Thank you!

**Comment by haroldiedema** [comment]
Try the global font scaling option in Dalamud. Setting that to 80% should already make a huge difference if everything looks too big right now.

As for the horizontal clocks; this is already possible:
![image](https://github.com/una-xiv/umbra/assets/567518/9f826b87-793a-4d69-8d1a-5339ba22262c)

**Comment by Yalessa** [comment]
That was indeed very helpful! In that case I'm happy I can change the font in Dalamud since it got very small there due to these changes xD Well now I'm aware of this connection, guess it was a lot to take in. That fixed it thank you!
