### ISSUE TITLE
[Feature Request] DTR bar intergration

### ISSUE THREAD

**Issue by LTS-FFXIV** [una-xiv/umbra#5]
![image](https://github.com/una-xiv/umbra/assets/127939494/576bcb4e-8320-45dd-a530-bc2a3b47e5a0)

Being able to add a widget to host dalamud server info bar information and interaction would be great, completely eliminating the need for the traditional info bar

Example plugins with DTR bar info and interactions: 
Mare Synchronous
LazyLoot
RotationSolverReborn
YesAlready

**Comment by haroldiedema** [comment]
Thanks for the suggestion!

I've already tinkered with this idea for a little bit, but there is currently no way in Dalamud itself to grab DTR bar entries. Once it becomes available, I'll add it in.

I'll leave this open until then.

**Comment by haroldiedema** [comment]
Update: A PR was just merged in Dalamud that allows me to implement a DTR bar widget. We just need to wait for a couple of days for it to be released to the public 😄

**Comment by haroldiedema** [comment]
Fixed!
