### ISSUE TITLE
[Feature Request] Add an Status Picker

### ISSUE THREAD

**Issue by Damdrara** [una-xiv/umbra#51]
It could show whatever your current status is as an icon and allow easy access to switching statuses - especially looking for an easy way to toggle RP mode personally, and see if it's on or not, but I imagine others might like afk and whatnot as well.

**Comment by haroldiedema** [comment]
I would need to research how to toggle these statuses. If anyone has any info on that, that'd be greatly appreciated! 😄

**Comment by Haselnussbomber** [comment]
This CS PR could be helpful for you: https://github.com/aers/FFXIVClientStructs/pull/860/files 🙂

I only tested it briefly with:

```cs
if (ImGui.Button("Set to Online"))
    InfoProxySearchComment.Instance()->SendOnlineStatusUpdate(0);

if (ImGui.Button("Set to Busy"))
    InfoProxySearchComment.Instance()->SendOnlineStatusUpdate(12);

if (ImGui.Button("Set to Role-playing"))
    InfoProxySearchComment.Instance()->SendOnlineStatusUpdate(22);
```

Keep in mind that you're about to send data to the server. Please take care and stay safe. 😅

Alternatively, you can open the Social Info window. See PR message for how.
