### ISSUE TITLE
[Feature Request] Emote Picker

### ISSUE THREAD

**Issue by Damdrara** [una-xiv/umbra#52]
...visually/functionally similar to the Gearset Switcher would be amazing, with some ordering, favoring, something of the likes.

Bonus points if you can make facial expressions loop until turned off, but that might be a bit beyond the scope of this plugin :)

**Comment by haroldiedema** [comment]
Yeah the "looping" isn't going to happen, albeit not dangerous at all, it does fall into the "automation" category, which is a no-no.

**Comment by haroldiedema** [comment]
This can now be achieved using a custom menu widget.
