### ISSUE TITLE
[Not a bug] But i have no idea where to write it ;-;

### ISSUE THREAD

**Issue by ZielonyQ** [una-xiv/umbra#53]
Ok im rly noob at github, and got no idea how to get the code for dalamud or im just stupid, probably both noob + stupid, any one can help/paste the code in readme? or a guide how to get the code ;c

**Comment by haroldiedema** [comment]
Why do you want the code for Dalamud?

**Comment by ZielonyQ** [comment]
nvm i find out its just testing plugin and i need to check the option in dalamud settings, just stupid like i said ;-;
