### ISSUE TITLE
[Bug] Line-wrap on world markers

### ISSUE THREAD

**Issue by krz0001** [una-xiv/umbra#54]
While farming in the Diadem with Umbra enabled, the World markers for gathering points are getting really, really long due to the amount of items and the length of their names.

Could line-wrap or a vertical display of items be enabled for long markers like those? 🙏 

![image](https://github.com/una-xiv/umbra/assets/18511031/4e6cd2f2-c42a-49c6-b1ed-271444541c7b)

**Comment by haroldiedema** [comment]
I've gone ahead and classified this as a bug, since that is most certainly _not_ intended behavior 😂
