### ISSUE TITLE
[Feature Request] Replace Left side with icons instead of text

### ISSUE THREAD

**Issue by LeranaRose** [una-xiv/umbra#56]
Option to replace the text 
![image](https://github.com/una-xiv/umbra/assets/122882276/ba6c11e2-3d0d-4037-a46f-d9d121162ed6)
with the icons with the vanilla menu icons (or even modded ones like mine)
![image](https://github.com/una-xiv/umbra/assets/122882276/2a630b95-5cfe-4e93-8447-1740c19498ff)

**Comment by haroldiedema** [comment]
I've implemented this feature, but there is one caveat with this that you should be aware of. The game officially uses a special single texture for the main command that contains all icons in a single file. Mods will probably use that as well.

Unfortunately, I cannot use that for this easily, so it is using the game icons instead. If those are modded, they will show the modded ones. Just be aware that most mod packs may choose to not modify these icons.
