### ISSUE TITLE
[Feature Request] Ability to swap left/right containers of the toolbar

### ISSUE THREAD

**Issue by SHOEGAZEssb** [una-xiv/umbra#57]
I think an option to have the main menu on the right side and the widgets on the left side would be nice

**Comment by haroldiedema** [comment]
I suppose this is fixed with the new addition of the layout editor, since you can freely swap all widgets from left-to-right and vice-versa.

![WhatsApp Image 2024-05-04 at 17 02 02_2f7910aa](https://github.com/una-xiv/umbra/assets/567518/431d3e8d-cd28-43ec-bafa-13b659023895)

**Comment by SHOEGAZEssb** [comment]
It's perfect, I love you
