### ISSUE TITLE
[Feature Request] Add an option to configure the update interval of Server Info bar entries

### ISSUE THREAD

**Issue by curtis846** [una-xiv/umbra#58]
Unsure if this is a bug or intended behaviour due to Umbra's inner workings. It's not a huge deal but just something i noticed.

https://imgur.com/a/gA4v54L

**Comment by curtis846** [comment]
Thanks for the reply and really sorry for using the wrong words. I was comparing against how the timer on the regular server bar behaves (https://imgur.com/a/FSnUq5W). It is probably due to the update interval of Umbra so timer doesn't tick smoothly.

**Comment by haroldiedema** [comment]
Ah yes, that explains it then!

I'll convert this into a feature request to allow you to configure the update interval manually if you desire.

**Comment by haroldiedema** [comment]
Actually, I'll just ramp up the interval instead. There's no real performance overhead anyway 😄
