### ISSUE TITLE
[Bug] DTR bar still disabled when toolbar is disabled

### ISSUE THREAD

**Issue by NLDGreen** [una-xiv/umbra#61]
I noticed that when I clicked Restart Umbra with the toolbar disabled, the native DTR bar shows, but when I re-enable the toolbar (which disables DTR), and re-disable it, the DTR bar is still disabled.
https://gyazo.com/4ed1f5e8aa90b445946a073bb9f31b61

_Originally posted by @NLDGreen in https://github.com/una-xiv/umbra/issues/50#issuecomment-2091878937_

**Comment by haroldiedema** [comment]
Yes, there is a separate option to just always show the native DTR bar. It's under toolbar settings -> server info bar.

**Comment by NLDGreen** [comment]
Yes but when I disable that setting, the DTR bar shows up even with the toolbar enabled
https://gyazo.com/cf64b34d609cde0e46f139045d8dbd06

**Comment by NLDGreen** [comment]
What I meant is for the following:

1. Whenever Umbra toolbar is disabled via /umbra-toggle Toolbar.Enabled, the DTR bar is enabled.
2. Whenever Umbra toolbar is re-enabled via the same command, the DTR bar is disabled, until 1. happens again.

**Comment by haroldiedema** [comment]
Gotcha! Now I understand.

When you get the next update (1.0.3.8+), make sure that the Hide option is still enabled. When you toggle the toolbar off, the server info bar will become visible again.
