### ISSUE TITLE
[Feature Request] Add a global scale option separate from Dalamud's Global Font Scale

### ISSUE THREAD

**Issue by Kaidesa** [una-xiv/umbra#63]
So, let me start by saying I absolutely love what you've done with Umbra so far, and I eagerly await to see what becomes of it.

That said, I'm getting up in age and my eyesight isn't the greatest.  It is exceptionally hard for me to make out the tiny text on the bar, making things like experience percentage and pretty much anything on the widgets with text hard to read.

I was hoping to see resizing or a global scaling option be possible with Umbra's toolbar, and maybe even a global scaling feature that would allow even menus to grow in size at the appropriate percentage.  This would help me, and I assume quite a few others out, greatly.

**Comment by haroldiedema** [comment]
Hi Kaidesa, glad you like it!

This is already possible by increasing the Global Font Scale setting in Dalamud settings in the "Look & Feel" tab. Since Umbra "borrows" fonts from Dalamud, I've deliberately chosen to let Dalamud handle the scaling to not over-complicate matters.

Please let me know if this option is sufficient for your use-case.

**Comment by Kaidesa** [comment]
So, you're correct.  Doing this definitely does allow for resizing of the Umbra toolbar.  Which in and of itself is pretty much what I needed.  The only issue I can think of is that resizing the Dalamud font to a size I would need (~130% scaling) makes all of the other plugins for Dalamud WAY too large.

I think it's mostly just an issue with the font sizes used in the smaller text segments within the toolbar itself.  Obviously, I understand that it's not a very highly demanded feature, but I definitely think that having it be a separate setting within the plugin itself would be the best option for those of us who have trouble reading the text in Umbra, but have an easy enough time already reading stuff inside of other Dalamud plugins.

Below is a picture depicting ~130% font scaling in Dalamud, and the effect it has on other plugins wwhen compared to the toolbar for Umbra.

![image](https://github.com/una-xiv/umbra/assets/2061070/d6d79a36-f3a9-4039-8f64-84f0b6fb97c0)

As an added gotcha, bumping the font scale up to this value actually adds a couple of pixels of padding to the bottom of the toolbar, lifting it up slightly, which is highly distracting when moving about.

It's not a super high priority or anything, but adding this feature would likely save some folks a headache, especially if they're running a lot of other plugins like myself.  Upping the overall font size in Dalamud fixes the problem, but also causes a severe lack of visible screen real estate for those of us going plugin-crazy, and the only reason I'd need/want to do that is just to read the smaller text in Umbra's toolbar.

**Comment by haroldiedema** [comment]
Alright, gotcha! I'll leave this open and see if I can cook something up in the near future 🙂
