### ISSUE TITLE
[Bug] Currency tab doesn't update when changing GC

### ISSUE THREAD

**Issue by foophoof** [una-xiv/umbra#67]
I just changed GC, and I noticed that the currency tab still lists the seal amount (and name) for my previous grand company, I went from the Immortal Flames to the Twin Adders, and the currency tab still shows Flame Seals instead of Serpent Seals:

![Screenshot from the currency tab in Umbra XIV showing Flame Seals](https://github.com/una-xiv/umbra/assets/22138688/eb8a12f6-f210-455c-b5ca-26461311e021)

![Screenshot from the currency window in FFXIV, showing Serpent Seals as the active seals](https://github.com/una-xiv/umbra/assets/22138688/bf344c02-15d1-4c90-8b0f-01688ac2a4ae)

**Comment by haroldiedema** [comment]
Ah, you should probably just logout and back in again due to some caching of values.

**Comment by foophoof** [comment]
"Restart Umbra" indeed worked.
