### ISSUE TITLE
[Feature Request] Simple Custom Menu Entry

### ISSUE THREAD

**Issue by imgidedin** [una-xiv/umbra#70]
Would it be possible to have the option for a custom menu entry? So we could add shortcut to our plugins? 

Maybe we could set the menu entry a custom name and add custom entries to it, like: Quests and it would execute /quests, etc? Kinda like QoLBar, but without all the bells and whistles, just a simple menu entry. You click, it runs that single command.

**Comment by haroldiedema** [comment]
Have to check with PAC to confirm whether this would be allowed or not.

**Comment by haroldiedema** [comment]
Checked on discord about possible restrictions. There don't seem to be any, so we're good to go. Now to think of a good way to implement this that would satisfy most users.

**Comment by haroldiedema** [comment]
The new 2.0 version adds support for custom toolbar widgets. These come in the form of 2 types:

1. Custom button - allows you to run any (single) chat command.
2. Use Item - Based on an ID of an item (you can get that using the "Show ID" tooltip option in Simple Tweaks)
