### ISSUE TITLE
[Bug] Location widget does not respect toolbar margin

### ISSUE THREAD

**Issue by gsapi** [una-xiv/umbra#71]
The location widget's horizontal position seems to be static and does not move to be in the center of the toolbar when the toolbar width changes, instead staying in the center of the screen. Would it be possible to have an option to keep it in the center of the toolbar for visual consistency?

**Comment by haroldiedema** [comment]
This is currently not possible no, because the location widget is in a special (centered) container. It will always sit in the middle of the screen.

I'll leave this open, but can't promise a fix for this on a short term.
