### ISSUE TITLE
[Bug] Location widget shows the wrong location

### ISSUE THREAD

**Issue by SabSparrow** [una-xiv/umbra#76]
Instead of the proper location, the location widget instead seems to always show a nearby landmark, and not always the closest one. In the Doman Enclave in particular, it shows The Watchtower whenever I'm south of the aetheryte. I suspect that the location widget just uses the closest map label, but has an offset problem in the Doman Enclave. This is inaccurate, it should fall back to the area name if a landmark is too far away. An example where that is an issue is the very east end of Castrum Occidens in Eastern La Noscea, where the location widget shows Hidden Falls or Agelyss Wise, because those map labels happen to be closer. The plugin "Where am I again?" does manage to identify the correct location, maybe that can help?

**Comment by haroldiedema** [comment]
Hi, thanks for the report!

Your assumption about it just picking the closest map label is correct. I'll have a look at "Where am I again?" to see how they do it.
