### ISSUE TITLE
[Feature Request] Current Repair and Spiritbond numbers.

### ISSUE THREAD

**Issue by shawnyve** [una-xiv/umbra#86]
Would love to see repair and spiritbond numbers on the bar as labels. Or alternately an alert like a red exclamation when one or the other is low or maxed where you can click to see the numbers in a popup. Also a right click that will open the appropriate menu to self repair or left click extraction for instance. I currently use repairme as a reference.

**Comment by haroldiedema** [comment]
Fixed in v2:

![image](https://github.com/una-xiv/umbra/assets/567518/c7195ac1-d0a7-4b2b-bcbb-22c84ddab8fd)

Also comes with a ton of customization options: 
![image](https://github.com/una-xiv/umbra/assets/567518/a43d9b1b-a645-4e11-b851-593ea149c8ed)
