### ISSUE TITLE
[Feature Request] Add mount music toggle to the volume widget

### ISSUE THREAD

**Issue by skullriot** [una-xiv/umbra#88]
I wanted to suggest the ability to toggle mount music via the volume widget. I think the best way to do it might be a middle click on the icon? Not a programmer so I won't claim to know how you could do it. 

Alternatively and/or additionally the volume menu could be increased in height and have toggle at the bottom, or increased in width for the same effect. I believe the only other volume/sound toggle that isn't represented is the mount music, I'm not sure if people would want toggles for "normal battle music" "Enable city-state BGM in residential areas" and/or "play system sounds while waiting for duty finder" but those are the other toggles in the system config menu. 

This functionality is already covered by AutoMountBGM along with advanced features, but those of us that would appreciate just a toggle would be thankful for this.

**Comment by haroldiedema** [comment]
Good idea! Will try to incorporate this in the upcoming V2.
