### ISSUE TITLE
[Feature Request] See through background

### ISSUE THREAD

**Issue by Megagalatkikarea2** [una-xiv/umbra#89]
hi there,
I'd like to request that we can change the opacity of the background of the toolbar. I'd really like it to be see-through

**Comment by Megagalatkikarea2** [comment]
![image_2024-05-16_095229450](https://github.com/una-xiv/umbra/assets/13068903/a2c0a8d6-d524-4363-9821-041cc8a5b0c8)

**Comment by haroldiedema** [comment]
That "line" is caused by the shadow effect. You can disable this in the toolbar settings.
