### ISSUE TITLE
Some i18n questions

### ISSUE THREAD

**Issue by AinaSnow** [una-xiv/umbra#9]
I've found some problems with i18n that only occur in other languages.
1. When the client language is Japanese, the currency button does not work, when I click the currency button, the weather menu pops up, after switching the client language to English, the problem disappeared. Initially, the problem is in the size of the menu buttons (because the menu buttons get their content directly from the game, but the Japanese menu names are longer, I'm not sure if this is the reason).
![30671ca77158a85a4fea17690d09db28](https://github.com/una-xiv/umbra/assets/15614550/5a2965ab-1d18-419f-aeea-c8a39d01265c)
![64925a7ae025325d1620e5aa612bc851](https://github.com/una-xiv/umbra/assets/15614550/791e526a-67f3-4aee-9248-1d7b1ec8102f)

2. Is it possible to add settings to i18n content without using the dalamud language settings obtained from dalamud? (This is kind of a niche issue I think, if my dalamud language is set to Chinese and the game language is Japanese, because there is no zh i18n file, it will automatically use the default value of English, I created my own i18n file, but because of the problem between dalamud and the game itself, some fonts will be missing, is it possible to add settings to the i18n of umbra? Can you add a separate setting for i18n in umbra?)

**Comment by haroldiedema** [comment]
Thanks for the findings!

The reason why the currency button does not work is because the weather/location widget is overlapping it. The widget in the center has a fixed size of over 500px, so on smaller screen resolutions/windows, they will overlap. I'll see if I can write a fix for this by making the fixed size a bit smaller.


> but because of the problem between dalamud and the game itself, some fonts will be missing
I don't really understand what you mean by this. If I understand correctly, you're asking for an options to override the client language in Umbra settings?

Most of the elements in Umbra come from the game itself (menu items, currency names, etc.) so they don't have custom translations. This means that if the selected language in Umbra does not match Dalamud's, there will be some mixed languages being used. I don't think there's much else you can do besides adding a zh.json file with the Chinese translations.

**Comment by AinaSnow** [comment]
The text in the plug-in is divided into two parts, one part is obtained directly from the game, and the other part is i18n content. I wonder if the user can choose what language to use for the i18n part instead of using dalamud's language setting.
The fonts in the i18n part are mixed between the game and dalamud itself, so if this part is a game, content will be lost. In fact, this problem does not only appear in Chinese. If there is no i18n in the game outside of JEDF, it will be an error.
![{93AA2D61-9999-4201-A5AB-19397FCEE273}](https://github.com/una-xiv/umbra/assets/15614550/29954983-511d-4307-b49f-1314a77f5483)
![QQ截图20240423152255](https://github.com/una-xiv/umbra/assets/15614550/4830b5f4-d3e4-4948-acd3-6797c575aec1)

**Comment by haroldiedema** [comment]
All elements in Umbra use the Axis font, which the game uses as well. I'm not quite sure how modifying the language would solve this to be honest 🤔

**Comment by AinaSnow** [comment]
My idea is to allow users to choose the language selection for the i18n part  for example https://github.com/Caraxi/SimpleTweaksPlugin
![2ff8607dce65ea2004e72706d18a62a1](https://github.com/una-xiv/umbra/assets/15614550/d97db204-978c-4609-853d-6590450da867)

**Comment by haroldiedema** [comment]
Yes, I understand that. I just don't understand how that is going to solve the missing glyphs in the screenshots you posted earlier?
Maybe I'm missing something.

**Comment by AinaSnow** [comment]
yep but Axis font The support for Chinese is not very good, so there will be deficiencies

**Comment by AinaSnow** [comment]
So my idea is if I can add a setting to allow i18n content to be different from the game itself language/dalamud language, example: game language: Japanese, dalamud language: Chinese, i18n language: Japanese What I do now is to create zh.json and Copy the content in ja.json to zh.json to complete

**Comment by haroldiedema** [comment]
> game language: Japanese, dalamud language: Chinese, i18n language: Japanese

Ah, now I understand. I was under the impression that you wanted to use zh in Umbra. I'll see if I can make an i18n switcher in the config. 😄

**Comment by AinaSnow** [comment]
thx
