### ISSUE TITLE
[Feature Request] Only show SS/S/A hunt markers

### ISSUE THREAD

**Issue by drejjmit** [una-xiv/umbra#92]
Since B and C doesn't award any Seals/Tomestones and are worthless unless you have that specific Hunt objective.
The ability to pick what hunt markers you want shown.

**Comment by haroldiedema** [comment]
![image](https://github.com/una-xiv/umbra/assets/567518/840b7675-7da4-480a-bba3-83ecbae7ad94)

Version 2.0 will have proper individual marker configuration. I've added toggle options for each rank respectively.
