### ISSUE TITLE
[Feature Request] Add opacity to toolbar when not mouse over

### ISSUE THREAD

**Issue by AltinaXIV** [una-xiv/umbra#93]
As a user, I think it would be nice to have some level of opacity in the bar until it is moused over. I would love to have a slider for this. It feels like it is squishing your gameplay space by being fully solid.

**Comment by AltinaXIV** [comment]
> Heya, I need a little more info on this.
> 
> Do you mean the opacity of the entire bar, including all widgets, or just the background colors?

Actually a really interesting question! So, the big thing for me is that I lose some viewable game space I had before. That being said, I think either of these would be a solution to the issue. Aesthetically, It's a bit hard for me to picture which of these would actually look better though. My gut says having the widgets remain a solid colour and having the background be transparent would look best but I would ultimately like to leave that decision up to you.

**Comment by haroldiedema** [comment]
I'll add color options for an "inactive" state of the toolbar that is used while the mouse is not near it.

This way you could add some semi-transaprent colors to it, but others could also use this to desaturate the bar to a grayish color, then make it colorful when the mouse is near it.
