### ISSUE TITLE
[Feature Request] Capitalize job/class names in the gearset swithcer

### ISSUE THREAD

**Issue by representativecheek7** [una-xiv/umbra#95]
It would be nice if it said a gearset was a "Level 90 Paladin" instead of "Level 90 paladin" or "Level 90 White Mage" instead of "Level 90 white mage" in the gearset switcher.

**Comment by haroldiedema** [comment]
![image](https://github.com/una-xiv/umbra/assets/567518/50020b85-9195-488f-8b5b-a281c5d0fd8b)

Fixed in 2.0
